# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d21ac457d82f829a819d24d124f78359"
application_url = "https://product-option-sets-production.up.railway.app"
embedded = true
name = "Products Options Extras"

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access-scopes
scopes = "read_files,read_products,write_files,write_products"

[auth]
redirect_urls = [
  "https://product-option-sets-production.up.railway.app/auth/callback",
  "https://product-option-sets-production.up.railway.app/auth/shopify/callback",
  "https://product-option-sets-production.up.railway.app/api/auth/callback"
]

[app_proxy]
url = "https://product-option-sets-production.up.railway.app/apps/product-options"
subpath = "product-options"
prefix = "apps"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false
