// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/apps/product-options": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/option-sets": {
    params: {};
  };
  "/app/option-sets/:id": {
    params: {
      "id": string;
    };
  };
  "/app/assignments": {
    params: {};
  };
  "/app/analytics": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/app/help": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/apps/product-options" | "/auth/login" | "/auth/*" | "/app" | "/app/option-sets" | "/app/option-sets/:id" | "/app/assignments" | "/app/analytics" | "/app/settings" | "/app/help";
  };
  "routes/webhooks.app.scopes_update.tsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.tsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/apps.product-options.tsx": {
    id: "routes/apps.product-options";
    page: "/apps/product-options";
  };
  "routes/auth.login/route.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/option-sets" | "/app/option-sets/:id" | "/app/assignments" | "/app/analytics" | "/app/settings" | "/app/help";
  };
  "routes/app.option-sets._index.tsx": {
    id: "routes/app.option-sets._index";
    page: "/app/option-sets";
  };
  "routes/app.option-sets.$id.tsx": {
    id: "routes/app.option-sets.$id";
    page: "/app/option-sets/:id";
  };
  "routes/app.assignments.tsx": {
    id: "routes/app.assignments";
    page: "/app/assignments";
  };
  "routes/app.analytics.tsx": {
    id: "routes/app.analytics";
    page: "/app/analytics";
  };
  "routes/app.settings.tsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.help.tsx": {
    id: "routes/app.help";
    page: "/app/help";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.tsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.tsx");
  "routes/apps.product-options": typeof import("./app/routes/apps.product-options.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.tsx");
  "routes/_index": typeof import("./app/routes/_index/route.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.option-sets._index": typeof import("./app/routes/app.option-sets._index.tsx");
  "routes/app.option-sets.$id": typeof import("./app/routes/app.option-sets.$id.tsx");
  "routes/app.assignments": typeof import("./app/routes/app.assignments.tsx");
  "routes/app.analytics": typeof import("./app/routes/app.analytics.tsx");
  "routes/app.settings": typeof import("./app/routes/app.settings.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
  "routes/app.help": typeof import("./app/routes/app.help.tsx");
};